### PR TITLE
adds trytes

### PR DESCRIPTION
**Pull request by tuddman**
- good for trinary based systems.  
- good for generating random seeds.

### CODE REVIEW

**Comment by weavejester** [comment]
Can you provide a little more information? Why is this useful?

**Comment by tuddman** [comment]
this whole project: https://github.com/iotaledger

yes, trinary is not as common as binary today.  no real reason it couldn't be, though.

**Comment by weavejester** [comment]
That seems a little too niche to me to be useful in crypto-random.

**Comment by tuddman** [comment]
today? yes. tomorrow? who knows.  

I've included this same functionality in domain-specific code.

you can ignore/reject this if you want. its just one `fn`

**Comment by tuddman** [comment]
`crypto-random` seemed like a good home for functions related to generating _cryptographically secure random numbers and strings_    for e.g. cryptocurrencies

**Comment by weavejester** [comment]
If this functionality becomes more commonplace, I'll take a look at it again. But for now, I don't think this functionality is in common enough usage to justify including it in crypto-random.

**Pull request closed without merging**
